title: Vasilis Kontonis
description: Senior Researcher at Microsoft Research
subtitle: Senior Researcher, Microsoft Research
logo: /assets/new.jpeg
# show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
